name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Web App Scaffold
        run: |
          flutter create my_app
          cd my_app
          flutter pub add home_widget http

      - name: Build Webview Runner
        run: |
          cd my_app
          flutter build ios --release --no-codesign
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r PS99Widget.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PS99Widget-IPA
          path: my_app/PS99Widget.ipa
